routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('layouts.app');
});

Route::middleware('auth')->group(function() {
    Route::resource('tasks', 'TasksController');
    Route::get('/home', 'HomeController@index')->name('home');
});

Auth::routes();

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Task
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property int $checked
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereChecked($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Task whereUpdatedAt($value)
 * @mixin \Eloquent
 */

class Task extends Model
{
    protected $fillable = [
        'title', 'description', 'user_id', 'checked'
    ];

    protected $attributes = [
        'checked' => false,
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * App\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'title', 'user_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tasks() {
        return $this->hasMany('App\Task', 'user_id');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $tasks = $user->tasks;
//      $tasks = Task::all();
        return view('tasks.index', ['allTasks'=>$tasks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> 'required',
            'description'=> 'required'
        ]);

        $tasks = new Task([
            'title'=> $request->get('title'),
            'description'=> $request->get('description'),
            'user_id' => Auth::id()
        ]);

        $tasks->save();

        return redirect('/tasks')->with('success', 'Task created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $tasks
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tasks = Task::find($id);
        return view('tasks.show', ['tasks'=>$tasks]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $tasks
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tasks = Task::find($id);
        return view('tasks.edit', compact('tasks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $tasks
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=> 'required',
            'description'=> 'required'
        ]);

        $tasks = Task::find($id);
        $tasks->title = $request->get('title');
        $tasks->description = $request->get('description');
        $tasks->save();

        return redirect('/tasks')->with('success', 'Task edited successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $tasks
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tasks = Task::find($id);
        $tasks->delete();
        return redirect('/tasks')->with('success', 'Task deleted successfully');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <title>@yield('title')</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-success mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">TODO list</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.index') }}">Tasks list</a>
                </li>
            </ul>
        </div>

        <div id="app">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </div>
</nav>

<div id="contentApp" class="container">
    @yield('content')
</div>


<script src="{{ asset('js/app.js') }}"></script>
</body>


</html>

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', 'Create task')

@section('content')
<div class="row">
    <div class="col-lg-6 mx-auto">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form method="POST" action="{{ route('tasks.store') }}">
            @csrf
                <div class="form-group">
                    <label for="task-title">Task name</label>
                    <input type="text" name="title"
                           value="{{ old('title') }}" class="form-control" id="exampleFormControlInput1">
                </div>

                <div class="form-group">
                    <label for="task-description">Task description</label>
                    <textarea class="form-control" name="description" id="task-description" rows="3">{{ old('description') }}</textarea>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>


@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit task '.$tasks->id)

@section('content')
    <div class="row">
        <div class="col-lg-6 mx-auto">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="POST" action="{{ route('tasks.update', $tasks) }}">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="task-title">Task name</label>
                    <input type="text" name="title"
                           value="{{ $tasks->title }}" class="form-control" id="exampleFormControlInput1">
                </div>

                <div class="form-group">
                    <label for="task-description">Task description</label>
                    <textarea class="form-control" name="description" id="task-description" rows="3">{{ $tasks->description }}</textarea>
                </div>
                <button type="submit" class="btn btn-success">Edit</button>
            </form>
        </div>
    </div>


@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', 'All tasks')

@section('content')

<a href="{{ route('tasks.create') }}" class="btn btn-success">Create task</a>

@if(session()->get('success'))
    <div class="alert alert-success mt-3">
        {{ session()->get('success') }}
    </div>
@endif


<div class="d-flex justify-content-start rounded-lg mt-4 mb-4 bg-dark text-light">
    <div class="col-sm-1 p-2 text-center">ID</div>
    <div class=" col-sm-2 p-2">Task name</div>
    <div class="p-2">Task description</div>
</div>


<p id="demo">Click me.</p>
<p>aloha</p>

<test-component></test-component>





@foreach($allTasks as $tasks)

    <div class="task d-flex justify-content-start bg-warning rounded-lg draggable mt-2 mb-2" draggable="true">

        <h5 class="col-sm-1 p-2 text-center align-self-center">{{$tasks->id}}.</h5>
        <div class="col-sm-2 p-2 align-self-center">{{$tasks->title}}</div>
        <div class="col-sm p-2 align-self-center">{{$tasks->description}}</div>

        <div class="d-inline-flex align-self-center">
            <div class="btn">
                <a href="{{ route('tasks.show', $tasks) }}" class="btn btn-success">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="btn">
                <a href="{{ route('tasks.edit', $tasks) }}" class="btn btn-primary">
                    <i class="fa fa-pencil"></i>
                </a>
            </div>
            <div class="btn">
                <form method="POST" action="{{ route('tasks.destroy', $tasks) }}">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </form>
            </div>
        </div>

                        {{-- HEY BRO WHATS UP WITH YOUR CODE --}}
        <div class="custom-control custom-checkbox align-self-center mr-2 ml-2">
            <form method="POST" action="{{ route('tasks.store', $tasks) }}">
                @csrf
                <input type="checkbox" class="custom-control-input" onclick="chbTest()"
                       @if ($tasks->checked === 1)
                       checked="checked"
                       @endif
                       id="{{$tasks->id}}">
                <label class="custom-control-label" for={{$tasks->id}}></label>
            </form>
        </div>

    </div>

@endforeach

@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('title', 'View task '.$tasks->id)

@section('content')

<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ $tasks->title }}</h4>
            <p class="card-text">{{ $tasks->description }}</p>
        </div>
    </div>
</div>

@endsection